{{- range $i, $issuer := .Values.certIssuers }}
{{- $s := $issuer.name }}
{{- $r := $issuer.issuerRef }}
{{- if not $r }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $s }}-selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-certificate 
spec:
  isCA: true
  commonName: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-certificate
  secretName: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
{{- if $r }}
    name: {{ $r }}
{{- else }}
    name: {{ template "redpanda.fullname" $ }}-{{ $s }}-selfsigned-issuer
{{- end }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-issuer
spec:
  ca:
    secretName: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-certificate 
---
{{- end }}
